language: java
jdk:
  - oraclejdk8
sudo: false
before_deploy: 
  - mvn install -DskipTests
  - export FILENAME=$(ls RML-Processor/target/RML-Processor-*.jar)

deploy:
  edge: true
  provider: releases
  api-key:
    - secure: blabla
  file: "${FILENAME}"
  on:
    tags: true
    all_branches: true
