language: java
jdk:
  - oraclejdk8
sudo: false
before_install: mvn install -DskipTests=true
deploy:
  edge: true
  provider: releases
  api-key:
    - secure: blabla
  file: RML-Processor/target/RML-Processor-0.2.jar
  on:
    tags: true
    all_branches: true
